### ISSUE TITLE
octave_zstd 1.0.2: src/configure is not executable

### ISSUE THREAD

**Issue by Schamschula** [CNOCTAVE/octave_zstd#1]
In `octave_zstd` 1.0.2 the `configure` file in `src` doesn't have the execute bits set.

See my workaround for MacPorts: https://github.com/macports/macports-ports/blob/master/octave/octave-zstd/Portfile

**Comment by CNOCTAVE** [comment]
ok. please PR. I will merge

**Comment by CNOCTAVE** [comment]
Btw my configure file is chmod a+x in Fedora. If this problem cannot be fixed under Linux, maybe you should pack under Mac, then I will release a special Mac tarball, like v1.0.2mac

**Comment by CNOCTAVE** [comment]
Try this tarball, is this tarball ok? https://github.com/CNOCTAVE/octave_zstd/releases/download/1.0.2/octave_zstd20241110.tar.gz

**Comment by Schamschula** [comment]
The new tarball has everything in the src folder set to execute! We only need it for the configure script.

BTW: I was referring to the `octave_zstd-1.0.2.tar.gz` tarball.

**Comment by CNOCTAVE** [comment]
ok. I already changed the new tarball to https://github.com/CNOCTAVE/octave_zstd/releases/download/1.0.2/octave_zstd.tar.gz , same to the original link.

**Comment by Schamschula** [comment]
Hmm. The checksum is the same.

**Comment by CNOCTAVE** [comment]
Yes. sha256sum only check text, it doesn't check filesystem things.

**Comment by Schamschula** [comment]
Unfortunately, I'm seeing the same permissions in the new tarball as that in the original one.

**Comment by CNOCTAVE** [comment]
In the new tarball I did
`# chmod a+x configure`
again.
Maybe you should pack a tarball on Mac and give me website, then I release a special Mac version.

**Comment by CNOCTAVE** [comment]
Think this, I compiled this tarball on Linux, Linux _make_ also need chmod a+x on configure, so this couldn't be mod problem, it should be filesystem incompatibility problem of Mac.

**Comment by CNOCTAVE** [comment]
![image](https://github.com/user-attachments/assets/d93c0f6a-b81c-41dd-b545-8367604fb269)
You are right. It looks like GitHub file host problem. Let me try to release a new version.

**Comment by Schamschula** [comment]
There is nothing Mac specific going on here! To extract MacPorts ran

`DEBUG: system:  cd "/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_octave_octave-zstd/octave-zstd/work" && /usr/bin/gzip -dc '/opt/local/var/macports/distfiles/octave-zstd/1.0.2_1/octave_zstd-1.0.2.tar.gz' | /usr/bin/tar -xf - `

I just noticed that MacPorts was again pulling the 1.0.2.tar.gz, rather than octave_zstd.tar.gz, which has the update permissions.

**Comment by CNOCTAVE** [comment]
Try this tarball. https://github.com/CNOCTAVE/octave_zstd/releases/download/1.0.3/octave_zstd.tar.gz . If this tarball is ok, I will release to Octave repo.

**Comment by Schamschula** [comment]
I'm not pulling in that tarball, but rather https://github.com/CNOCTAVE/octave_zstd/archive/refs/tags/1.0.3.tar.gz which is unchanged.

In the meantime I locally made the corrected tarball.

**Comment by CNOCTAVE** [comment]
ok. now I delete the v1.0.3 release.

**Comment by Schamschula** [comment]
Here's my version of the tarball:

[octave_zstd-1.0.2.tar.gz](https://github.com/user-attachments/files/17689269/octave_zstd-1.0.2.tar.gz)

**Comment by Schamschula** [comment]
It gave me a clean build and install.

**Comment by CNOCTAVE** [comment]
I just invite you as a collaborator, so you may add Mac tarballs in any release as needed. Then, you may add tarball with your preferred filename, even directly replace my tarball, etc., all are ok.

**Comment by CNOCTAVE** [comment]
I updated your tarball. Try your build is ok or not.

**Comment by CNOCTAVE** [comment]
![image](https://github.com/user-attachments/assets/e0eceac9-7bc6-4328-9de3-160287bacc80)
Your tarball is broken. How could this happen?

**Comment by CNOCTAVE** [comment]
![image](https://github.com/user-attachments/assets/17f3640c-f24c-4ebd-81a0-982b1c049d46)
And, as this Octave source code, when you pack tarball, you cannot pack docs/ folder, or Octave will throw an error of this.
![image](https://github.com/user-attachments/assets/f2b7c43c-a1ce-4f34-8b1c-d36d5eef75dc)
You should only pack these files. Please repack.

**Comment by CNOCTAVE** [comment]
With your tarball I cannot pass Octave repo CI. https://github.com/gnu-octave/packages/pull/503 . If no workaround, after 1 day I will rollback the original tarball.

**Comment by Schamschula** [comment]
Other than the permissions on a single file, nothing else has changed!

I have the following checksums

```
checksums           rmd160  394e10adfcc408d62a7a6fed4526561616a03303 \
                    sha256  9ee1ca702e92ddf342af59793b7babd6c09868e68de970cd83633fd7fac96514 \
                    size    705269

```

**Comment by CNOCTAVE** [comment]
> ![image](https://private-user-images.githubusercontent.com/184102101/384642827-17f3640c-f24c-4ebd-81a0-982b1c049d46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDk2NzMsIm5iZiI6MTczMTIwOTM3MywicGF0aCI6Ii8xODQxMDIxMDEvMzg0NjQyODI3LTE3ZjM2NDBjLWYyNGMtNGViZC04MWEwLTk4MmIxYzA0OWQ0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwMzI5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDViN2NkMzAzMTBmYjVjMGQ3OTUxMjg2ZDljNTE1MTgwNzk2YjIyNWFlNzIyZTIzOGE4Mzg2MTdlMDMzMjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wizXwrMc3zUw7KI58Nxa-s2ttLsV7MVHcguuGWKBc5w) And, as this Octave source code, when you pack tarball, you cannot pack docs/ folder, or Octave will throw an error of this. ![image](https://private-user-images.githubusercontent.com/184102101/384642908-f2b7c43c-a1ce-4f34-8b1c-d36d5eef75dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDk2NzMsIm5iZiI6MTczMTIwOTM3MywicGF0aCI6Ii8xODQxMDIxMDEvMzg0NjQyOTA4LWYyYjdjNDNjLWExY2UtNGYzNC04YjFjLWQzNmQ1ZWVmNzVkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwMzI5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjhhMjIzYjljMmY0MWM2YjQ1MTRiMTRkZmQzMjU4ZmQwYzMzYjlkMzAyNTM0ZGE2OTJlZjRlMDc5ZDFlMjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3NU5GPP2FgvAGPAMTU3F5beh2xIEdWcXbJpyYtiQiZs) You should only pack these files. Please repack.

If you won't repack following this guide, I will rollback, because your tarball cannot be installed on Octave.

**Comment by Schamschula** [comment]
I'll have to investigate. All I did is make a tarball of the package with the modified file permissions. No other changes.

Note: I maintain ports of over ninety octave packages for MacPorts. This the only one so far that has had a permissions issue.

**Comment by CNOCTAVE** [comment]
My tarball can pass Octave repo CI, but yours can't. That's weird. Please investigate.

**Comment by siko1056** [comment]
@CNOCTAVE and @Schamschula I think we start getting into a rabbit hole.

I downloaded the tarballs on my local system (Ubuntu 24.04) and extracted them with `tar` and with the ui tool and the outcome is very weird
```
d-wx--x--x  3 siko1056 siko1056       4096 Oct 10 21:53 octave_zstd
-rw-rw-r--  1 siko1056 siko1056      61066 Nov 13 07:14 octave_zstd.tar.gz
```
```
drwxrwxr-x  4 siko1056 siko1056       4096 Oct 16 21:28 octave_zstd-1.0.2
drwxrwxr-x  4 root     root           4096 Oct 16 21:28 octave_zstd-1.0.2-ui
-rw-rw-r--  1 siko1056 siko1056     702303 Nov 13 07:14 octave_zstd-1.0.2.tar.gz
```
However, all available archives seem bogged regarding file permissions:
- `octave_zstd-1.0.2.tar.gz` (GitHub created) extracts with root permissions, depending on the tool
- `octave_zstd.tar.gz` (self-packaged) has no read permission

@CNOCTAVE Why do you create an extra tarball if GitHub creates it already for you automatically?

On Octave Packages you use the self-packaged version
```
https://github.com/CNOCTAVE/octave_zstd/releases/download/1.0.2/octave_zstd.tar.gz
```
Not the GitHub generated archive
```
https://github.com/CNOCTAVE/octave_zstd/archive/refs/tags/1.0.2.tar.gz
```

@Schamschula  I think the Octave CI went through a tiny slit of possibility when using the Ubuntu `tar` tool it somehow got a "useful" version of the package extracted.  Even on Ubuntu changing the packing tool (preserving certain file attributes most likely) the package becomes immediately not installable.

@CNOCTAVE I am not sure how to proceed from here.  On what system are you working on?  Would it be possible to review the file permission on your local system and the settings in your `.gitconfig`?

**Comment by siko1056** [comment]
Just for reference on my system (which is close to CI):

GitHub packaged release tarball.
```
>> pkg install -verbose https://github.com/CNOCTAVE/octave_zstd/archive/refs/tags/1.0.2.tar.gz
mkdir (/tmp/oct-fG2R71)
untar (/tmp/oct-ejavLL/1.0.2.tar.gz, /tmp/oct-fG2R71)
sh: 1: ./configure: Permission denied

error: pkg: error running the configure script for octave_zstd
error: called from
    configure_make at line 101 column 9
    install at line 202 column 7
    pkg at line 619 column 9
```

@CNOCTAVE -packaged release tarball
```
>> pkg install -verbose https://github.com/CNOCTAVE/octave_zstd/releases/download/1.0.2/octave_zstd.tar.gz
mkdir (/tmp/oct-yMD1d6)
untar (/tmp/oct-8g02za/octave_zstd.tar.gz, /tmp/oct-yMD1d6)
checking for a sed that does not truncate output... /usr/bin/sed
checking for octave... /usr/bin/octave-9.2.0
checking for mkoctfile... /usr/bin/mkoctfile-9.2.0 --verbose
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether feval is in the octave namespace... yes
checking whether octave value has Octave style is* methods... yes
checking whether octave::execution_exception has message member... yes
checking whether dim_vector has xelem method... yes
checking whether range is in the octave namespace... yes
checking whether templated lambda functions accept '&const int'... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
make: Entering directory '/tmp/oct-yMD1d6/octave_zstd/src'
/usr/bin/mkoctfile-9.2.0 --verbose  -Wall -g -O2 zstd_compress.cc -lzstd
/usr/bin/mkoctfile-9.2.0 --verbose  -Wall -g -O2 zstd_decompress.cc -lzstd
/usr/bin/mkoctfile-9.2.0 --verbose  -Wall -g -O2 zstd_compress_string.cc -lzstd
/usr/bin/mkoctfile-9.2.0 --verbose  -Wall -g -O2 zstd_decompress_string.cc -lzstd
g++ -c  -fPIC -I/usr/include/octave-9.2.0/octave/.. -I/usr/include/octave-9.2.0/octave  -pthread -fopenmp -g -O2 -g -Wall -O2   zstd_compress.cc -o /tmp/oct-AfiysL.o
g++ -c  -fPIC -I/usr/include/octave-9.2.0/octave/.. -I/usr/include/octave-9.2.0/octave  -pthread -fopenmp -g -O2 -g -Wall -O2   zstd_decompress.cc -o /tmp/oct-K89SGN.o
g++ -c  -fPIC -I/usr/include/octave-9.2.0/octave/.. -I/usr/include/octave-9.2.0/octave  -pthread -fopenmp -g -O2 -g -Wall -O2   zstd_compress_string.cc -o /tmp/oct-yIrkeg.o
g++ -c  -fPIC -I/usr/include/octave-9.2.0/octave/.. -I/usr/include/octave-9.2.0/octave  -pthread -fopenmp -g -O2 -g -Wall -O2   zstd_decompress_string.cc -o /tmp/oct-EZ1oDj.o
g++ -I/usr/include/octave-9.2.0/octave/.. -I/usr/include/octave-9.2.0/octave  -pthread -fopenmp -g -O2 -g  -Wall -O2 -o zstd_compress_string.oct  /tmp/oct-yIrkeg.o   -lzstd -shared -Wl,-Bsymbolic  -shared -Wl,-Bsymbolic
g++ -I/usr/include/octave-9.2.0/octave/.. -I/usr/include/octave-9.2.0/octave  -pthread -fopenmp -g -O2 -g  -Wall -O2 -o zstd_decompress_string.oct  /tmp/oct-EZ1oDj.o   -lzstd -shared -Wl,-Bsymbolic  -shared -Wl,-Bsymbolic
g++ -I/usr/include/octave-9.2.0/octave/.. -I/usr/include/octave-9.2.0/octave  -pthread -fopenmp -g -O2 -g  -Wall -O2 -o zstd_decompress.oct  /tmp/oct-K89SGN.o   -lzstd -shared -Wl,-Bsymbolic  -shared -Wl,-Bsymbolic
g++ -I/usr/include/octave-9.2.0/octave/.. -I/usr/include/octave-9.2.0/octave  -pthread -fopenmp -g -O2 -g  -Wall -O2 -o zstd_compress.oct  /tmp/oct-AfiysL.o   -lzstd -shared -Wl,-Bsymbolic  -shared -Wl,-Bsymbolic
make: Leaving directory '/tmp/oct-yMD1d6/octave_zstd/src'
copyfile /tmp/oct-yMD1d6/octave_zstd/src/zstd_compress.oct /tmp/oct-yMD1d6/octave_zstd/src/zstd_compress_string.oct/tmp/oct-yMD1d6/octave_zstd/src/zstd_decompress.oct /tmp/oct-yMD1d6/octave_zstd/src/zstd_decompress_string.oct /tmp/oct-yMD1d6/octave_zstd/inst/x86_64-pc-linux-gnu-api-v59

warning: couldn't clean up after my self: Permission denied
For information about changes from previous versions of the octave_zstd package, run 'news octave_zstd'.
```

Note the `warning: couldn't clean up after my self: Permission denied`, which shows that the package has read permissions not set when the archive is extracted:
```
>> ls -al /tmp
total 540
drwxrwxrwt 1 root     root       4096 Nov 12 22:46 .
drwxr-xr-x 1 root     root       4096 Nov 12 22:14 ..
drwxr-xr-x 2 root     root       4096 Oct 15 23:14 hsperfdata_root
drwxrwxr-x 2 siko1056 siko1056   4096 Nov 12 22:14 .oct-qhelp-G9BJUV
-rw-r--r-- 1 siko1056 siko1056 528384 Nov 12 22:14 oct-qhelp-G9BJUV
drwxrwxr-x 3 siko1056 siko1056   4096 Nov 12 22:45 oct-yMD1d6
drwxrwxr-x 3 siko1056 siko1056   4096 Nov 12 22:16 oct-ZsUXsX
```

```
>> ls -al /tmp/oct-yMD1d6/octave_zstd
ls: cannot open directory '/tmp/oct-yMD1d6/octave_zstd': Permission denied

>> system ("sudo ls -al /tmp/oct-yMD1d6/octave_zstd")
total 68
d-wx--x--x 4 siko1056 siko1056  4096 Nov 12 22:45 .
drwxrwxr-x 3 siko1056 siko1056  4096 Nov 12 22:45 ..
-rwxr-xr-x 1 siko1056 siko1056 35147 Mar 23  2022 COPYING
-rwxr-xr-x 1 siko1056 siko1056   362 Oct 16 12:28 DESCRIPTION
-rwxr-xr-x 1 siko1056 siko1056   199 Sep 30 11:06 INDEX
drwxrwxr-x 3 siko1056 siko1056  4096 Nov 12 22:46 inst
-rwxr-xr-x 1 siko1056 siko1056   551 Oct 16 12:27 NEWS
-rwxr-xr-x 1 siko1056 siko1056  1241 Oct  7 22:47 octave_zstd.metainfo.xml
drwxr-xr-x 3 siko1056 siko1056  4096 Nov 12 22:46 src
```
